name: build
concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true
on: 
    push:
        paths-ignore:
        - '**/*.md'    
    workflow_dispatch:
jobs:
    build-python:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --requirement requirements.txt
                pip install jupyter "Ipython<9"
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap01.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap02.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap03.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap04.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap05.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap06.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap07.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap08.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap09.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap10.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap12.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap13.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap14.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap16.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap17.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap19.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap20.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap21.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap22.ipynb
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap23.ipynb
            # slow notebooks
            - run: cd src/chapters; jupyter nbconvert --to python --execute chap11.ipynb
            # currently failing
            # - run: cd src/chapters; jupyter nbconvert --to python --execute chap15.ipynb
            # - run: cd src/chapters; jupyter nbconvert --to python --execute chap18.ipynb
